apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: goof
  name: goof
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: goof
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: goof
    spec:
      containers:
        - env:
            - name: DOCKER
              value: "1"
          image: purpledobie/goof:demo
          name: goof
          ports:
            - containerPort: 3001
            - containerPort: 9229
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: goof
  name: goof
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "9229"
      port: 9229
      targetPort: 9229
  selector:
    io.kompose.service: goof
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: goof-mongo
  name: goof-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: goof-mongo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: goof-mongo
    spec:
      containers:
        - image: mongo
          name: goof-mongo
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: goof-mongo
  name: goof-mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: goof-mongo
status:
  loadBalancer: {}
