apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof
      tier: frontend
  template:
    metadata:
      labels:
        app: goof
        tier: frontend
    spec:
      containers:
        - name: goof
          image: <<REPO>>/goof:latest #Edit with your container registry repo
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3001
            - containerPort: 9229
          env:
            - name: DOCKER
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof-image
      tier: frontend
  template:
    metadata:
      labels:
        app: goof-image
        tier: frontend
    spec:
      containers:
        - name: goof-image
          image: <<REPO>>/goof-image:latest #Edit with your container registry repo
          imagePullPolicy: Always
          ports:
            - containerPort: 3112
            - containerPort: 31337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof
      tier: backend
  template:
    metadata:
      labels:
        app: goof
        tier: backend
    spec:
      containers:
        - name: goof-mongo
          image: mongo
          ports:
            - containerPort: 27017
