name: Snyk Container Scan
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build a Docker image
      run: docker build -t example .

    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: example
        args: --file=Dockerfile

    - name: Add Secure Code Warrior contextual training to SARIF
      uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1
      with:
        inputSarifFile: snyk.sarif
        outputSarifFile: snyk.processed.sarif
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.processed.sarif
