name: Snyk Delta Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  security-open-source:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 18.4
        - name: Installing snyk-delta and dependencies
          run: npm i -g snyk-delta
        - uses: snyk/actions/setup@master
        - name: Snyk Test
          run: snyk test --json --print-deps | snyk-delta
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
