name: snyk-labs/action example - Snyk SCM Issues to Github Issues
on: workflow_dispatch
  # - push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk-labs/actions/snyk-scm-issues-to-gh-issues@main

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          REMOTE_REPO_URL: ${{ github.repositoryUrl }}
